defs:
  noise_levels: &noise_levels
    type: config
    name: noise_levels
    of:
      train:
        model:
          feedback_noise_std: [0.01, 0.1]
          motor_noise_std:    [0.01, 0.1]
      model:
        feedback_noise_std: [0.01, 0.1]
        motor_noise_std:    [0.01, 0.1]

  delays: &delays
    type: config
    name: delays
    of:
      train.model.feedback_delay_steps: [0, 5]

  damping: &damping
    type: config
    name: damping
    of:
      train.model.damping: [0, 10]
  
  tau_rise: &tau_rise
    type: config
    name: tau_rise
    of:
      train.model.tau_rise: [0.0, 0.05]

  disturbance_types: &disturbance_types
    type: cases
    of:
      - type: config
        name: curl-curl
        of:
          train:
            pert:
              type: curl
              std: !Literal [0.0, 1.5]

      - type: config
        name: constant-constant
        of:
          train:
            pert:
              type: constant
              std: !Literal [0, 1]



SPEC: 
  - part2.feedback_perts:
      type: product
      of: 
        - *damping
        - *tau_rise
        - *noise_levels
        - *delays
        - *disturbance_types