# reusable definitions (ignored by parser)
defs:
  base: &base
    type: config
    name: base
    of:
      train: 
        model:
          hidden_size: 180

        pert:
          type: gusts
          duration_mean: 8
          n_expected: 4
          std: !Literal [0, 2, 4]

        task:
          type: delayed_reach
          n_steps: 130
          epoch_len_ranges: !Literal
            - [10, 11]   # pre-target on
            - [5, 20]  # target on, pre-movement
          target_on_epochs: !Literal [1, 2]
          hold_epochs: !Literal [0, 1]
          move_epochs: !Literal [2]

  loss_update_start: &loss_update_start
    type: config 
    name: loss_update_start 
    of: 
      loss_update.start_iteration: [0, 5000, 10000]

  pert_std: &pert_std 
    type: config 
    name: pert_std 
    of: 
      pert.std: [0, 4]

  loss_weights: &loss_weights 
    type: config 
    name: loss_weights 
    of: 

      loss_update: 
        target_ratio: [0.1, 1.0]

  loss_structure: &loss_structure 
    type: config 
    name: loss_structure 
    of: 
      loss: 
        effector_pos_mid.start_step_after_go: [40, 0]
        effector_vel_mid.start_step_after_go: [40, 0]

  p_catch_trial: &p_catch_trial
    type: config
    name: p_catch_trial
    of:
      train: 
        task:
          p_catch_trial: 0.5  #! [0.6, 0.9]  

# actual per-module specs
SPEC:
  - part1.plant_perts:
      type: product
      of:
        - *base
        - *pert_std
        - *loss_structure
        - *loss_weights
        - *p_catch_trial
        - *loss_update_start