# reusable definitions (ignored by parser)
defs:
  noise_levels: &noise_levels
    type: config
    name: noise_levels
    of:
      model:
        feedback_noise_std: [0.01, 0.1]
        motor_noise_std:    [0.01, 0.1]

  feedback_delays: &feedback_delays
    type: config
    name: feedback_delays
    of:
      model:
        feedback_delay_steps: [0, 5]

  damping: &damping
    type: config
    name: damping
    of:
      model:
        damping: [0, 10]

  tau_rise: &tau_rise
    type: config
    name: tau_rise
    of:
      model:
        tau_rise: [0, 0.05]

  disturbance_types: &disturbance_types
    type: cases
    name: disturbance_types
    of:
      - type: config
        name: curl
        of:
          pert:
            type: curl
            std: [0.0, 0.5, 1.0, 1.5]
      - type: config
        name: constant
        of:
          pert:
            type: constant
            std: [0, 0.01, 0.1, 1]

# actual per-module specs
SPEC:
  - part2:
      type: product
      of:
        - *noise_levels
        - *feedback_delays
        - *damping
        - *tau_rise
        - *disturbance_types
