# reusable definitions (ignored by parser)
defs:
  base: &base
    type: config
    name: base
    of:
      pert:
        type: gusts
        duration_mean: 8
        n_expected: 4
        std: [0, 4, 8]

      task:
        type: delayed_reach
        epoch_len_ranges: !Literal
          - [10, 11]   # pre-target on
          - [5, 20]  # target on, pre-movement
        target_on_epochs: !Literal [1, 2]
        hold_epochs: !Literal [0, 1]
        move_epochs: !Literal [2]

  loss_weights: &loss_weights 
    type: config 
    name: loss_weights 
    of: 
      loss:
        weights:
          effector_hold_pos: 1.0
          effector_hold_vel: 1.0
          goal_hit_in_window: [0.1, 1.0] #, 5.0, 0.1, 1.0, 5.0, 0.1, 1.0, 5.0, 0.1, 1.0, 5.0]  #!
          effector_pos: 1.0
          effector_pos_late: 1.0
          effector_vel_late: 1.0
          nn_output: 1e-5
          nn_hidden: 1e-5
        goal_hit_in_window:
          window_bounds: !Literal [60, 80]
          softmin_tau: [0.05, 0.05] #, 0.05, 0.05, 0.05, 0.05, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2]  #!
          post_pos_sigma_t: 5  #!
          weights: 
            pos: 1.0 
            vel: 1.0
            post_pos: [0.25, 0.25] #, 0.25, 1.0, 1.0, 1.0, 0.25, 0.25, 0.25, 1.0, 1.0, 1.0] #!
            # late_pos: 1.0  #!

  p_catch_trial: &p_catch_trial
    type: config
    name: p_catch_trial
    of:
      task:
        p_catch_trial: [0.6, 0.9]

  # noise_levels: &realism
  #   type: config
  #   name: realism
  #   of:
  #     model:
  #       feedback_noise_std: [0.01, 0.1]
  #       motor_noise_std:    [0.01, 0.1]
  #       feedback_delay_steps: [0, 5]
  #       damping: [0, 10]
  #       tau_rise: [0, 0.05]

# actual per-module specs
SPEC:
  - part1:
      type: product
      of:
        - *base
        - *loss_weights
        - *p_catch_trial
        # - *realism

  # - part2:
  #     type: product
  #     of:
  #       - *noise_levels
  #       - *feedback_delays
  #       - *damping
  #       - *tau_rise