"""Stable identifiers for RLRMP loss objectives."""

CS_FULL_ANALYTICAL_QRF_LOSS_OBJECTIVE = "full_analytical_qrf"
CS_PARTIAL_NET_FORCE_FILTER_LOSS_OBJECTIVE = "partial_net_output_force_filter"
CS_PARTIAL_FEEDBAX_LOSS_OBJECTIVE = "partial_feedbax_terms"
CS_LOSS_OBJECTIVES = (
    CS_PARTIAL_FEEDBAX_LOSS_OBJECTIVE,
    CS_PARTIAL_NET_FORCE_FILTER_LOSS_OBJECTIVE,
    CS_FULL_ANALYTICAL_QRF_LOSS_OBJECTIVE,
)

__all__ = [
    "CS_FULL_ANALYTICAL_QRF_LOSS_OBJECTIVE",
    "CS_LOSS_OBJECTIVES",
    "CS_PARTIAL_FEEDBAX_LOSS_OBJECTIVE",
    "CS_PARTIAL_NET_FORCE_FILTER_LOSS_OBJECTIVE",
]
