#  Hyperparameters that uniquely identify the model(s)/training run(s) to analyze
train:
  pert:  
    # type: curl
    # std: [0.0, 0.5, 1.0, 1.5]  
    type: gusts
    std: [0, 4, 8]
    duration_mean: 8
    n_expected: 4

# sisu: [-3., -2., -1., 0., 1., 2., 3.]
sisu: [0.0, 1.0]

model:
  feedback_noise_std: null
  motor_noise_std: null

task:  # Passed to the base task constructor
  n_steps: 150
  eval_n: 10
  variants:
    full:
      eval_grid_n: 2
      eval_n_directions: 16
      # eval_reach_length: 0.5
    small:
      eval_grid_n: 1
      eval_n_directions: 7
      # eval_reach_length: 0.5

pert:
  # null -> same as during training, e.g. load.train.pert.type in this case
  type: null 
  amp: [0.0, 4.0, 8.0] 
  # constant -> [0.0, 0.4],


analyses:
  center_out_sets: 
    i_replicate: null
