#  Hyperparameters that uniquely identify the model(s)/training run(s) to analyze
train:
  pert:  
    type: gusts
    std: [0.0, 4.0]
    n_expected: 4
    duration_mean: 8
    # type: constant
    # std: [0.0, 0.1, 1.0]
  task:
    type: delayed_reach
    n_steps: 130
    p_catch_trial: 0.5

  loss: 
    weights:
      goal_hit_in_window: 0.0  #! or 5, or 0.1
      nn_hidden: 1e-6
      nn_output: 1e-6
    goal_hit_in_window: 
      softmin_tau: 0.05  #! or 0.05
      weights:
        post_pos: 0.25  #! or 0.25
      
  
model:
  feedback_noise_std: null
  motor_noise_std: null
  
task:  # Passed to the base task constructor
  n_steps: null
  eval_n: 10
  variants:
    full:
      eval_grid_n: 1 #! 2
      eval_n_directions:  24  #!24
      eval_reach_length: 0.5
    small:
      eval_grid_n: 1
      eval_n_directions: 7
      eval_reach_length: 0.5

pert:
  type: gusts
  amp: [0.0, 8.0, 16.0] 

analyses:
  center_out_sets: 
    i_replicate: null  # null -> best replicate
    
  
  